#!/usr/bin/env python3
"""Synchronize Obsidian-authored docs to the GitHub Wiki."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

from link_convert import convert_tree


def run_git(args: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=cwd, check=check, text=True, capture_output=True)


def ensure_wiki_repo(wiki_dir: Path, remote: str) -> None:
    if (wiki_dir / ".git").exists():
        return

    if wiki_dir.exists():
        shutil.rmtree(wiki_dir)

    clone_result = subprocess.run(["git", "clone", remote, str(wiki_dir)], text=True)
    if clone_result.returncode == 0:
        return

    wiki_dir.mkdir(parents=True, exist_ok=True)
    run_git(["init"], wiki_dir)
    run_git(["remote", "add", "origin", remote], wiki_dir)
    (wiki_dir / "Home.md").write_text("# ShadowHound Wiki\n\nAutogenerated from /docs.\n", encoding="utf-8")
    run_git(["add", "Home.md"], wiki_dir)
    run_git(["commit", "-m", "Initialize wiki"], wiki_dir)
    run_git(["branch", "-M", "main"], wiki_dir)
    run_git(["push", "-u", "origin", "main"], wiki_dir)


def stage_converted(conversion_dir: Path, wiki_dir: Path) -> None:
    for path in wiki_dir.iterdir():
        if path.name == ".git":
            continue
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()

    for src_path in conversion_dir.rglob("*"):
        if src_path.is_dir():
            continue
        rel_path = src_path.relative_to(conversion_dir)
        dest_path = wiki_dir / rel_path
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_path)


def sync_wiki(docs_dir: Path, wiki_dir: Path, remote: str) -> None:
    ensure_wiki_repo(wiki_dir, remote)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)
        convert_tree(docs_dir, tmp_path)
        home_src = tmp_path / "index.md"
        home_dest = tmp_path / "Home.md"
        if home_src.exists() and not home_dest.exists():
            shutil.copy2(home_src, home_dest)
        stage_converted(tmp_path, wiki_dir)

    run_git(["add", "--all"], wiki_dir)
    status = run_git(["status", "--porcelain"], wiki_dir)
    if status.stdout.strip():
        run_git(["commit", "-m", "Update wiki from docs"], wiki_dir)
        run_git(["push"], wiki_dir)
    else:
        print("Wiki is up to date; no changes to push.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Synchronize Obsidian docs with the GitHub Wiki.")
    parser.add_argument("--docs", default=Path("docs"), type=Path, help="Source docs directory.")
    parser.add_argument("--wiki", default=Path("wiki"), type=Path, help="Local wiki repository path.")
    parser.add_argument("--remote", required=True, help="Git remote for the wiki repository.")
    args = parser.parse_args()

    sync_wiki(args.docs.resolve(), args.wiki.resolve(), args.remote)


if __name__ == "__main__":
    main()
